"""add desired_account_type as user table col

Revision ID: 2545ed06d920
Revises: 9b283adcc66f
Create Date: 2021-10-03 11:27:40.103988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2545ed06d920'
down_revision = '9b283adcc66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    desired_account_type = postgresql.ENUM('TOURIST', 'TRAVEL GUIDE', 'ADMIN', name='desired_account_type')
    desired_account_type.create(op.get_bind())
    op.add_column(
        'user', sa.Column(
            'desired_account_type', postgresql.ENUM('ADMIN', 'TRAVEL GUIDE', 'TOURIST', name='desired_account_type'),
            nullable=True
        )
    )
    op.alter_column(
        'user', 'account_type', existing_type=postgresql.ENUM('ADMIN', 'TRAVEL GUIDE', 'TOURIST', name='account_type'),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('ADMIN', 'TRAVEL GUIDE', 'TOURIST', name='account_type'),
               nullable=False)
    op.drop_column('user', 'desired_account_type')
    # ### end Alembic commands ###
