"""rename password col into password_hash and delete confirmed password

Revision ID: 9b283adcc66f
Revises: b2974053473b
Create Date: 2021-10-02 22:02:41.614666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b283adcc66f'
down_revision = 'b2974053473b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=150), nullable=False))
    op.drop_column('user', 'password')
    op.drop_column('user', 'confirmed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
